<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ttcn3</string>
	</array>
	<key>name</key>
	<string>TTCN3</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>keyword</string>
			<key>match</key>
			<string>var|boolean|inout|return\s+|:=|\?|&lt;|\+|-&gt;|\s+to\s+|integer|type record length|omit|#ifndef|#endif|^\s*if|#else|import from|^module|system|runs on|not\s+|\s+all</string>
			<key>name</key>
			<string>keyword.other.ttcn3</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>testcase</string>
			<key>match</key>
			<string>(testcase)\s+([a-zA-Z][a-zA-Z0-9_]+)</string>
			<key>name</key>
			<string>keyword.testcase.ttcn3</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>function definiton</string>
			<key>match</key>
			<string>function\s+([a-zA-Z][a-zA-Z0-9_]+)</string>
			<key>name</key>
			<string>keyword.function.ttcn3</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>built in function</string>
			<key>match</key>
			<string>ispresent|valueof|lengthof</string>
			<key>name</key>
			<string>entity.name.function.ttcn3</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>none</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>none</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>user definded constants</string>
			<key>match</key>
			<string>GLO_FALSE|GLO_TRUE|false|\s+\d+</string>
			<key>name</key>
			<string>constant.character.ttcn3</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>template</string>
			<key>match</key>
			<string>\s+template</string>
			<key>name</key>
			<string>storage.type.ttcn3</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>string</string>
			<key>match</key>
			<string>\"[\/a-zA-Z][\/a-zA-Z0-9_\.]+\"</string>
			<key>name</key>
			<string>string.ttcn3</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>comment</string>
			<key>match</key>
			<string>\/\*.*|.*\*\/|\*.*|\/\/.*</string>
			<key>name</key>
			<string>comment.ttcn3</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ttcn3</string>
	<key>uuid</key>
	<string>b80100fe-b212-41e8-a023-e83d354fe6f7</string>
</dict>
</plist>
